Merge dev into master (#16)
* Add notebook mBERT finetuning on token classification task (thai-ner)

* Add sefr_cut version 0.2 to requirements.txt

* Add tensorflow >= 2.0.0 to requirements.txt

* Add numpy >= 1.19.2 to requirements.txt

* Add wrapt to requirements.text and remove numpy

* Specify version for wrapt

* Remove version specified for wrapt

* Make prepare_for_tokenization returns replaced text

* Revert commit

* Add additinal function for SequenceClassificationDataset to support loading from Dataset class

* Add  @classmethod to SequenceClassificationDataset.from_dataset

* Change from self to cls

* Passing argument

* Assign tokenizer to class attribute

* Refactor code for SequenceClassificationDataset class

* Fix error: local variable 'input_ids', 'attention_masks' referenced before assignment

* Add 3 additinoal class attributes

* Add attribute data_dat to cls()

* Assign default value to be from arguments

* Change from pad_to_mas_length to padding='max_length' due to deprecation warning of transformers (FutureWarning).

* Add a script for seqeunce classification finetuning

* Change from evaluate_during_training to evaluation_strategy due to deprecation warning (FutureWarning)

* Set prediction_loss_only to False

* Fix wrong method and argument name

* Add new argument: logging_steps

* Add argument fp16 , for switching from fp32 training to fp16 training

* Output summary of model loaded

* Format log output

* Format code

* Modify prepare_for_tokenization to accept user's supplied space_token (default: "<_>")

* Add two additional arguments

- prepare_for_tokenization : Specify either to apply the method `prepare_for_tokenization` or not for given text inputs. As some pretrained model don't replace space with another special token.
- space_token : allow user's supplied space token to make the space token match the particular model special symbols

* Fix error, and add output logging

* Fix error, wrong position of arugment

* Refactor: Rename from `sefr`  to `sefr_cut`

* Add batched=False for sefr pre-tokenization

* Fix error: TypeError: must be str, not list

* Fix error: TypeError: must be str, not list

* Add two new args --target_class and --max_seq_length

* Fix logical error , warmup steps computation

* Support for SPM tokenizer models that are built with CamembertTokenizer

* Refactor: rename key for DATASET_METADATA

* Add new keys
- task
- split_names

* Print tokenizer detail

* Add a new utility function for accessing value from an nested Dict object

The function is implemented to support nested structire of `generated_reviews_enth` dataset.

* Remove unused argument (as the task is defined in at DATASET_METADATA)

* Add two Tokenizer class to support mBERT and XLMRoberta finetuning

* Handle the case when arg: keys has the data type as str

* Fix module importing

* Refactor: passing only on `args` object insted of multiple arguments

* Add arguments to parser

* Print warmup_ratio

* Format code

* Add 12 column names of the labels in `prachathai67k` dataset

* Format code

* Modify SequenceClassificationDataset to support multi-label classification task

* Add RobertaForMultiLabelSequenceClassification class

* Add fucntionality for model finetuning on prachathai67k (multi-label classification task)

* Print message show current state

* Refactor: move Task class to `thai2transformers.conf`

* Add condition for Task.MULTILABEL_CLS to output a dictionary with a key named "label_ids" which is meant for multiple labels

ref: https://github.com/huggingface/transformers/blob/master/src/transformers/data/data_collator.py

* Fix error

* Debug: reduce number of examples for testing

* Pass `task` to SequenceClassificationDataset constructor

* Fix error: labels_ids contain a flatten Tensor (1D) instead of 2d Tensor

* Debug: add debug message

* Remove debug message

* Revert to previous version

* Make logits and labels Tensor to be the original shape

* Fix error, TypeError: 'Tensor' object is not callable

* Change dtypr of labels_ids Tensor to torch.float

* Add metrics for multi-label classification

* Add a variable threshold as a paramter for `multilabel_classification_metrics` function

* Add a condition for trainer initialization for different classification task

* Set a paramter of TrainingArguments, `logging_first_step`, to False

* Add a return type for `process_transformers`

* Add a functionality to apply a custom preprocessing function on texts

* Refactor: rename from `preprocess_fn` to `preprocessor`

* Refactor: rename from `preprocess_fn` to `preprocessor` and solve syntax error

* Add Bert, and XLMRoberta model subclass for multi-label classification tasks

* Rename subclass name to "BertForMultiLabelSequenceClassification"

* Add an autoclass named `AutoModelForMultiLabelSequenceClassification` for multi-label classification

* Fix typo, wrong model name

* Import config class

* Move AutoModelForMultiLabelSequenceClassification to `thai2transformers.auto`

* Refactor: use AutoModelForMultiLabelSequenceClassification
to initialize multi-label classification model

* Change argument name and type of argument

* Fix wrong naming

* Suport model finetuning for mBERT and XLMRoberta

* Refactor: Change order of parser.add_argument

* Fix error, ImportError: cannot import name 'BertClassificationHead'

* Not use AutoConfig.from_pretrained but from prefined dictionary

* Rename model_name

* Fix logical error

* Fix typo

* Assisgn num_labels to Config class

* Change to fast tokenizer

* Fix issue where prepare_for_tokenization is not pased to _build_from_dataset

* Change from `load_config` to `from_pretrained` as it will load pretrained weights

* Pass config

* FIx error, incorrect model identifier listed on 'https://huggingface.co/models'

* Remove debuging code (small dataset)

* Remove a term "-2" for the max_length of seqeuence

* Add condition to use max_position_embeddings
if  args.max_seq_length is not specified

* Refer to DATSET_METADATA.split_names insted of hardcoded

* Fix syntax error

* Add condition to print message in validation se t exist

* Fix syntax error

* Add condition to handle dataset with no validation set

* Pass max_length and bs to SequenceClassificationDataset

* Add an option for XLMRobert large model finetuning

* Add a bash script to run finetuning script

* Add xlm-robert-large to fintuning script

* Append messages to the log file

* Add WANDB environment variables

* Rename path

* Create a directory

* Use chmod command to allow wandb logs the result

* Fix syntax error and format code

* Fix syntax error

* Fix error

* Fix missing argument

* Add messages

* Fix error

* Refactor name "LOG_DIR" to "TF_LOG_DIR"

* Fix syntax rror

* Create directory

* Specify metric_key_prefix to test

* Log wandb summary for evaluation result on test set

* Assign wandb_run_name to HF Trainer

* Save last checkpoint

* FIx wrong position of argument run_name

* Fix error , where metric_key_prefix is not available for 3.4.0

* Change hyperparams

* Change evaluation_strategy to "epoch"

* Save best checkpoint

* Change default value of argument

* Remove save_steps and eval_steps

* Add a script for fp16 training

* Add a new task

* Perform train set spliting for `wongnai_reviews`

* Update help message

* Print message

* Add param DATASET

* Format code

* Add datasets to requirements,txt

* Print message

* Add new split for wongnai_reviews

* Print max_seq_length

* Fix syntax error

* Change padding from 'max_length' to True

* Add a new key "huggingface_dataset_name"
for huggingface datasets referencing

* Add LabelEncoder to transfrom values in
dataset label column

* Fix syntax error

* Fix error
TypeError: get_dict_val() missing 1 required positional argument: 'keys'

* Set pading to 'max_length'

* Add DataCollatorWithPadding and not pad to max_length

* specify arg name

* Format code

* Add condition

* Set seed for reproducibility

* Add debug message

* Modify type checking for preprocessor

* Use torch.backends.cudnn.deterministic and torch.backends.cudnn.benchmark instead
(for torch==1.5.0)

* Allow user to suppy custom space_token

* Assign pre_rules from seq_cls_finetune.py

* Save model before evaluation on test set

* Add debug message

* Print first 2 items

* Add debug messages

* Add debug message

* Remove prepare_for_tokenization functionality

* Use trainer.predict instead of trainer.evaluate

* Add debug message

* Change logic of get_dict_val

* Change from list to a tuple of two values

* Add a script with a new set of hyperparams:

- N_EPOCHs = 3
- BATCH_SIZE = 32
- LR = 3e-5
- WARMUP_RATIO = 0.1

* Set logging_steps to 50

* Add new script for public language model finetuning

* Provide the replace_spaces function if space_token is specified.
Otherwise, returns an identity function.

* Not specify space_token

* Disable a functionalty to download `prachathai67k` from direct link

As a result, the script will download from
`datasets.load_dataset()` instead.

* Add two scripts for multi-label classification

* Assign n_labels to multilabel_classification_metrics

* Modify multilabel_classification_metrics to select a set of
best threshold for each label before computing
all the metrics

* Assign n_labels to multilabel_classification_metrics
with partial

* Set label_encoder to None for multi-label

* Apply sigmoid function to the
output layer of multi-label classification head

* Add condition for label_encoder debug message printing

* Remove Sigmoid class from
multi-label classification models

* Applt sigmoid function to predicetd logits

* Change feature column of prachathai67k

* Set return_dict to True

* Manually define sigmoid function instead

* Set dataload_drop_last to "False" ( !! Major change )

The experiment should be redo after this commit
As the trainer will drop last incompleted batch,
the evaluation result may be incorrect.

* Fix wrong variable name

* Remove code for debugging

* Remove unused code

* Add condition to support metrics
for multiclass and multilabel classification

* Install datsets from commit ID

* Merge branch `pre-dev` to `dev` (#6)

- Add new tokenizers including `newmm`, `ssg`, and `sefr_cut`
- Add a functionality to cache numericalized word tokens
- Add scripts for masked language model pre-training 
- Add scripts to download, extract and cleanThai Wikipedia corpus
- Add documentation to reproduce Thai Wikipedia RoBERTa BASE pre-training experiments.

Co-authored-by: Zinc Orca <zinc.orca@gmail.com>

* add nbsvm and crf scripts/notebooks for downstream tasks

* add train_sequence_ multiclass_thai2fit notebooks and scripts

* add batch_size argument

* test on test set not validation

* Fix an issue where datasets.map
can't access text from a nested dictionary

* combine sequence classification for thai2fit

* Not check length of tuple

* Change data tyoe from tuple to list

* Change datatype from tuple to list

* Fix type checking error

* Move tokenize_function outside of Dataset.map

* Fix syntax error

* Fiix syntaxx error

* Join text input column name to fix a problem
when applying dataset.map

* Add accuracy micro metrics

* Handle case where tokenizer is not `sefr_cut`

* Specify "metric_for_best_model" as "f1_macro"
for multi-label classification task

* add seqeval_classification_metrics

* edit seqeval metric names

* separate ner and pos

* remove old token classification

* change name of script ner->pos

* add train_token_ner_crf script

* fix bugs train_token scripts

* format token notes

* doc: update documentation

* Remove unused scripts

* Rename finetuning script from "seq_cls_finetuning.py"
to "train_sequence_classification_lm_finetuning.py"

* Remove debug messages

* Remove duplicated keys and values

* update ThaiNER best model performance

* update thainer results

* update crf results/notebooks/scripts  with short thainer

* Merge pre-dev to dev branch (#14)

* Add run_ner.py script for training ner_tags on thainer. This should be able to train other tags too such as pos_tags.

* Fix preprocessing dataset to input_ids part (tokenize). This should fix performance of a model with subword tokenizer. The old version wrongly assign tokenizer id to a token that appear at start and at the end with the same id. For example, ('##a', 'a') are different ids even though it corresponding to the same letter just at different position. Add new metrics (functionally the same just different form).

* Add metrics support for other label than NER.

* Show example of how to caculate warmup_steps in run_ner.sh.

* Add lst20 dataset and move cached_tokenize function in run_ner.py.

* Add dummytest dataset option to run_ner.py for quick testing.

* Add script as a template for running multiple experimentals at once.

* Fix wrong output_dir in run_ner_all.py

* Add a condition for Camembert Tokenizer with
user supplied "space_token"

* Specify the version of datasets to 1.2.0

For the branch, it is required to installed datasets with this version
to preserve compatability with the existing code
in the finetuning script (run_ner.py)

(ref commit ID: commit d5abb6156b81fb36d00e8a92678a6b86a1653012)

* Add a new script for token cls finetuning
with roberthai-95g-spm
CamembertTokenizer

* Specify tokenizer class

* Remove env variable WANDB_PROJECT

* Make directory

* Fix typos

* Modify script to allow user supplied space_token

* Change max_length to 416

* Modify logging dir and add wandb run name

* Add functionality to apply lowercasing rule

* Remove tag 'ไม่ยืนยัน'

* Format code

* Allow user to specify exp version

* CHange max sequence length

* Change max_length to 510

* Add an argument to either apply text lowercasing
 rule or not.

* Set max_length to 416

* Add lowercase argument

* Add FakeSefrCutTokenizer option which use sefr_cache internally as a simeple lookup table. The lookup table creation process is in sefr_cache.py, this process can be offloaded to device with large amount of cpu cores to speed up the process.

* Merge from `dev`

* Remove unused files

* Add documentation for LM finetuning

* Rename file

* Add documentation

* Update documentation for token classification

* Update documentation

* Merge notebooks

* Remove unused scripts

* Refactor: rename argument name to be the same as
 Huggingface's Trainer

1. Change from `max_seq_length` to `max_length`
2. Chnage from `wandb_run_name` to `run_name`

* Format code

* Fix typo and update documentation

* Update documentation

- Add a section for showing example log output
- Fix errors in documentation

* Update documentation

- Add example log output
- FIx typo in filename

* Add an option to apply lowercase or not

* Add new training script

* Remove type

* Add v3 script with batch size

* Select best threshold based on f1-macro

* Disable seqeval

* Select only generated_reviews_enth-review_star

* Add debug message

* Modyfy get_dict_val

* Fix error accessing value with get_dict_val
for sefr_cut

* Fix syntax error

* Return first element

* set batched to False

* Fix error

* Select first element

* Return list

* Add script v4

* Change LR to 3e-5

* Add a training script for fp16 bz16 (versiob 4)

* Add option to exclude record that have too long token using mbert tokenizer as a base line tokenizer (since mbert is one of the tokenizer that give out a lot of tokens).

* Add mbert tokenizer filter.

* Update script

* Use single quote instead fo double quote

* Change type to bool

* Remove redundant code

* Set device_batch_size to 32

* Add spm camembert checkpoint 360k version

* Add new script for spm_camembert ckp360k

* Fix style.
Change space_token default to use SPACE_TOKEN instead of hardcode value.
Remove Thainer/LST20 dataset hack.
Add default value for pre_tokenize, cached_tokenize, preprocess.

* Hard code pretokenize space_token in mbert length filter.

* Add a function _process_transformers
for input text preprocessing

* Change argument name from `wandb_run_name`
to `run_name`

* Add an arugment `lowercase` to perofrm
text lowercasing

* Add new proprocessing rule, `replace_rep_after`

* Refer to function `_process_transformers` instead

* Fix an error when training with seft_cut token

* Remove duplicated code

* Add spm95g run script.

* Set manual seed for torch and numpy

* Add seed.

* Change run_ner_all.sh hyperparameter.

* Refactor: remove duplicated code

* Fix module import pathing issue when import thai2transformers.tokenizers from top level directory.

* Refactor: remove duplicated code

* Define thai2transformers.tokenizers.SPACE_TOKEN
as DEFAULT_SPACE_TOKEN

* Remove unused files

* Remove unused notebooks

* Remove unused files

* Update description

* [doc] Fix typo

* [doc] Format code

* [doc] Update description

* [doc] fix grammatical error

* [doc] Capitalize abbreviation

* [doc] Remove empty newlines at the end of document

* [doc] Add instruction to install require libraries

* Revert to the previous version, using relative path appending

* [doc] format markdown text

* [doc] Remove duplicated segment

* [doc] format markdown text

* [doc] Format markdown text

* [doc] Format markdown text

* Remove debugging message

Co-authored-by: Zinc Orca <zinc.orca@gmail.com>

* change space token to <_>

* Update readme (#15)

* Update README.md

* Remove <br> tag

* Fix grammatical errors and format document

Co-authored-by: Zinc Orca <zinc.orca@gmail.com>
Co-authored-by: charin <charin@central.tech>
Co-authored-by: Charin <charin.polpanumas@datatouille.org>
Co-authored-by: cstorm125 <admin@packer-5f8541a7-8538-1e8a-dcde-9b6c0efc0a78.c.deeplearning-platform.internal>